version: '3.9'

services:
  mongo:
    container_name: mongo
    image: mongo:5.0.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - C:\Users\adalb\workspace\Web Development\Databases\mongo\gym-routine:/data/db

  api:
    container_name: api
    restart: always
    build: .
    ports:
      - 5000:5000
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
    depends_on: 
      - mongo
    volumes:
      - ./src:/app/src